$path = "shortList.csv"
$adminUpn = "kevin.blanchard@llamasoft.com"


$debugLog = "logs/licensesLog.txt"
$exceptionsLog = "logs/licensesExceptions.txt"

$LicensesWithTeams = New-MsolLicenseOptions -AccountSkuId supplychainguru:ENTERPRISEPACK -DisabledPlans "POWER_VIRTUAL_AGENTS_O365_P2", "CDS_O365_P2", "PROJECT_O365_P2", "DYN365_CDS_O365_P2", "MICROSOFTBOOKINGS", "KAIZALA_O365_P3", "MICROSOFT_SEARCH", "WHITEBOARD_PLAN2", "MIP_S_CLP1", "MYANALYTICS_P2", "BPOS_S_TODO_2", "FORMS_PLAN_E3", "STREAM_O365_E3", "Deskless", "FLOW_O365_P2", "POWERAPPS_O365_P2", "PROJECTWORKMANAGEMENT", "SWAY", "INTUNE_O365", "YAMMER_ENTERPRISE", "RMS_S_ENTERPRISE", "OFFICESUBSCRIPTION", "MCOSTANDARD", "SHAREPOINTWAC", "SHAREPOINTENTERPRISE" 
$LicensesWithoutTeams = New-MsolLicenseOptions -AccountSkuId supplychainguru:ENTERPRISEPACK -DisabledPlans "POWER_VIRTUAL_AGENTS_O365_P2", "CDS_O365_P2", "PROJECT_O365_P2", "DYN365_CDS_O365_P2", "MICROSOFTBOOKINGS", "KAIZALA_O365_P3", "MICROSOFT_SEARCH", "WHITEBOARD_PLAN2", "MIP_S_CLP1", "MYANALYTICS_P2", "BPOS_S_TODO_2", "FORMS_PLAN_E3", "STREAM_O365_E3", "Deskless", "FLOW_O365_P2", "POWERAPPS_O365_P2", "TEAMS1", "PROJECTWORKMANAGEMENT", "SWAY", "INTUNE_O365", "YAMMER_ENTERPRISE", "RMS_S_ENTERPRISE", "OFFICESUBSCRIPTION", "MCOSTANDARD", "SHAREPOINTWAC", "SHAREPOINTENTERPRISE" 
